site_name: SODA Community
site_url: https://soda.community
site_description: SODA Community - ソフトウェア開発における品質向上と効率化を目指すコミュニティ
site_author: SODA Community
docs_dir: deck
theme:
  name: material
  language: ja
  logo: assets/logo.svg
  favicon: assets/favicon.png

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/soda-community

plugins:
  - social:
      cards: true
      cards_layout_options:
        background_color: "#2e2e2e"
        color: "#ffffff"
  - meta:
      meta_file: '**/.meta.yml'

extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Inception Deck: deck.md
