site_name: SODA Community
site_url: https://soda.community
site_description: SODA Community - ソフトウェア開発における品質向上と効率化を目指すコミュニティ
docs_dir: deck
theme:
  name: material
  language: ja
  logo: assets/logo.svg
  favicon: assets/favicon.png

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/soda-community
  meta:
    - name: og:type
      content: website
    - name: og:title
      content: SODA Community
    - name: og:description
      content: ソフトウェア開発における品質向上と効率化を目指すコミュニティ
    - name: og:image
      content: https://soda.community/assets/favicon.png
    - name: og:url
      content: https://soda.community
    - name: twitter:card
      content: summary_large_image
    - name: twitter:title
      content: SODA Community
    - name: twitter:description
      content: ソフトウェア開発における品質向上と効率化を目指すコミュニティ
    - name: twitter:image
      content: https://soda.community/assets/favicon.png

extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Inception Deck: deck.md
