site_name: SODA Community
docs_dir: deck
theme:
  name: material
  language: ja
  logo: assets/logo.svg
  favicon: assets/favicon.png

extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Inception Deck: deck.md
